#ifndef P2P_ERR_H
#define P2P_ERR_H

#define P2P_ERR_OK 0
#define P2P_ERR_GENERIC -1
#define P2P_ERR_DENIED -2
#define P2P_ERR_NULL_PARAM -3
#define P2P_ERR_INVALID_PARAM -4
#define P2P_ERR_FULL_PEERS -5
#define P2P_ERR_NOT_EMPTY -6
#define P2P_ERR_RETRY -7

#define P2P_ERR_SEND -6
#define P2P_ERR_RECV -7
#define P2P_ERR_LARGE_PACKET -8
#define P2P_ERR_NOTFOUND -9


#define P2P_ERR_AUTH_ALREADY -10



#define P2P_ERR_NORANDOM -100
#define P2P_ERR_RSA_INIT -101
#define P2P_ERR_RSA_GEN -102
#define P2P_ERR_RSA_EXP -103


#define P2P_ERR_NET_NODATA -200
#define P2P_ERR_NET_DISCONNECTED -201
#define P2P_ERR_NET_BAD_PACKET -202
#define P2P_ERR_NET_SMALL_BUF -203
#define P2P_ERR_NET_SEND -204
#define P2P_ERR_NET_RECV -205


#define P2P_ERR_CACHE_REOPEN -300
#define P2P_ERR_CACHE_BAD_FORMAT -301
#define P2P_ERR_CACHE_NOIP -302

#endif
